<?php

use Illuminate\Database\Seeder;

class FoldersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('folders')->insert([
            ['name' => 'All Tags', 'is_system_autogenerated' => true],
        ]);
        
        DB::table('folders')->insert([
            ['name' => 'Auto Generated', 'folder_parent_id' => 1, 'is_system_autogenerated' => true],
        ]);
        
        DB::table('folders')->insert([
            ['name' => 'Purposes', 'folder_parent_id' => 2, 'is_system_autogenerated' => true],
            ['name' => 'Campaigns', 'folder_parent_id' => 2, 'is_system_autogenerated' => true],
            ['name' => 'Groups', 'folder_parent_id' => 2, 'is_system_autogenerated' => true],
            ['name' => 'Events', 'folder_parent_id' => 2, 'is_system_autogenerated' => true],
            ['name' => 'Forms', 'folder_parent_id' => 2, 'is_system_autogenerated' => true],
            ['name' => 'Transaction Paths', 'folder_parent_id' => 2, 'is_system_autogenerated' => true],
            ['name' => 'Devices', 'folder_parent_id' => 2, 'is_system_autogenerated' => true],
        ]);
        
        DB::table('folders')->insert([
            ['name' => 'All Groups', 'type' => 'GROUPS', 'is_system_autogenerated' => true],
        ]);
    }
}
