<?php

use Illuminate\Database\Seeder;

class TagsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tags')->insert([
            ['name' => 'Donor', 'folder_id' => 1, 'is_system_autogenerated' => true],
            ['name' => 'Missionary', 'folder_id' => 1, 'is_system_autogenerated' => true],
            ['name' => 'Fundriser', 'folder_id' => 1, 'is_system_autogenerated' => true],
            ['name' => 'Recurring Transactions', 'folder_id' => 1, 'is_system_autogenerated' => true],
            ['name' => 'Group member', 'folder_id' => 1, 'is_system_autogenerated' => true],
            ['name' => 'Group leader', 'folder_id' => 1, 'is_system_autogenerated' => true],
            ['name' => 'Pledger', 'folder_id' => 1, 'is_system_autogenerated' => true],
            ['name' => 'Form Respondent', 'folder_id' => 1, 'is_system_autogenerated' => true],
        ]);
    }
}
