@if(!$folder->is_system_autogenerated)
{{ Form::model($folder, ['route' => ['folders.destroy', $folder->id], 'method' => 'delete', 'id'=>'delete-form-'.$folder->id]) }}
<button type="button" class="btn btn-link text-danger delete-folder" data-name="{{$folder->name}}" data-form="#delete-form-{{$folder->id}}" data-toggle="modal" data-target="#delete-folder-modal">
    <span class="fa fa-trash"></span>
</button>
{{ Form::hidden('uid',  Crypt::encrypt($folder->id)) }}

{{ Form::close() }}
@endif