@if(!$folder->is_system_autogenerated)
{{ Form::model($folder, ['route' => ['folders.update', $folder->id], 'method' => 'put', 'id'=>'update-form-'.$folder->id]) }}
<button type="button" class="btn btn-link edit-folder" data-name="{{ $folder->name }}" data-form="#update-form-{{$folder->id}}" data-toggle="modal" data-target="#edit-folder-modal">
    <span class="fa fa-edit"></span>
</button>
{{ Form::hidden('uid',  Crypt::encrypt($folder->id)) }}
{{ Form::hidden('name', $folder->name) }}
{{ Form::hidden('current_folder_parent_id', $folder->id) }}
{{ Form::hidden('folder_parent_id', $root->id) }}

{{ Form::close() }}
@endif