@if(!$tag->is_system_autogenerated)
{{ Form::model($tag, ['route' => ['tags.destroy', $tag->id], 'method' => 'delete', 'id'=>'delete-form-'.$tag->id]) }}
<button type="button" class="btn btn-link text-danger delete-tag" data-name="{{$tag->name}}" data-form="#delete-form-{{$tag->id}}" data-toggle="modal" data-target="#delete-tag-modal">
    <span class="fa fa-trash"></span>
</button>
{{ Form::hidden('uid',  Crypt::encrypt($tag->id)) }}

{{ Form::close() }}
@endif